########### Spring Boot Configuration Start ###########

server:
  # the server port
  address: 0.0.0.0
  port: 8110


logging:
  # logback file location
  config: classpath:logback.xml

########### Spring Boot Configuration End ###########


########### Eagle Configuration Start ###########
eagle:

  # eagle-ui user, default is admin
  user: root

  # eagle-ui password, default is admin
  pass: 123456

########### Eagle Configuration End ###########